name: Backend Tests and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Run Go tests
        run: go test -v -coverprofile=coverage.out -covermode=atomic -coverpkg=./internal/...,./middleware/... ./test/unit/...
  
  e2e-tests:
    needs: test-and-lint
    uses: mauroav21/AutPruebLogin/.github/workflows/e2e-login-tests.yml@main
    secrets: inherit